name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          
      - name: Install dependencies
        working-directory: ./web
        run: yarn install
        
      - name: Build ui-framework
        working-directory: ./web/ui-framework
        run: |
          yarn install
          yarn build
          cp -r dist ../node_modules/@phanna/ui-framework/
          
      - name: Build project
        working-directory: ./web
        run: VITE_ENVIRONMENT=production yarn build
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          
      - name: Build Flutter web app
        working-directory: ./flutter_sample
        run: |
          flutter pub get
          flutter build web --release --base-href /project-ui-framework/flutter-sample/
          mkdir -p ../web/dist/production/contents/flutter-sample
          cp -r build/web/* ../web/dist/production/contents/flutter-sample/
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './web/dist/production/contents'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
